argo:
  version: 3.0.2
  ingress_host: argo
  minio_image: docker.io/minio/minio:latest
  events:
    enabled: true
    version: 1.3.1
  # oauth:
  #   provider: keycloak
  #   keycloak:
  #     realm: default
  # s3:
  #   accesskey: argo
  #   secretkey: P4ssw0rd
  #   bucket: argo-artifacts