{
 "title": "Cockroach Storage",
 "description": "Storage dashboard: storage availability.",
 "tags": [ "cockroach" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster name",
    "query": "sys_uptime{job=~\".*cockroachdb-public\"}"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(sys_uptime{job=~\".*cockroachdb-public\",cluster=\"$cluster\"},instance)"
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Capacity: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(sum(capacity{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance)) - sum(sum(capacity_available{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(sum(capacity{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Capacity"
    }
   ]
  },
  {
   "title": "Capacity Used: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "(sum(capacity{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance) - sum(capacity_available{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance)) / sum(capacity{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Percentage of capacity used per node: All",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - sum(capacity_available{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance) / sum(capacity{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Percentage of capacity used per node: All",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "1 - sum(capacity_available{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance) / sum(capacity{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(sum(livebytes{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Live"
    },
    {
     "expr": "sum(sum(sysbytes{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "Live Bytes: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sum(livebytes{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Raft log commit latency: 99th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "raft_process_logcommit_latency:rate1m:quantile_99{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read Amplification: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "avg(rocksdb_read_amplification{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Raft command commit latency: 99th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "raft_process_commandcommit_latency:rate1m:quantile_99{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RocksDB SSTables: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "sum(rocksdb_num_sstables{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read Amplification: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(avg(rocksdb_read_amplification{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Read Amplification"
    }
   ]
  },
  {
   "title": "File descriptor usage: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "sum(sys_fd_open{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance) / sum(sys_fd_softlimit{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Raft Engine Read Amplification: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(avg(raft_rocksdb_read_amplification{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Raft Engine Read Amplification"
    }
   ]
  },
  {
   "title": "RocksDB SSTables: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(rocksdb_num_sstables{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "SSTables"
    }
   ]
  },
  {
   "title": "Raft RocksDB SSTables: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(raft_rocksdb_num_sstables{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "SSTables"
    }
   ]
  },
  {
   "title": "RocksDB cache hit rate: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rocksdb_block_cache_hits{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"} / (rocksdb_block_cache_hits{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"} + rocksdb_block_cache_misses{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "{{instance}}:{{store}}"
    }
   ]
  },
  {
   "title": "Raft RocksDB cache hit rate: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "raft_rocksdb_block_cache_hits{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"} / (raft_rocksdb_block_cache_hits{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"} + raft_rocksdb_block_cache_misses{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "{{instance}}:{{store}}"
    }
   ]
  },
  {
   "title": "File Descriptors: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(sys_fd_open{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Open FDs"
    },
    {
     "expr": "sum(sum(sys_fd_softlimit{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Limit"
    }
   ]
  }
 ]
}
{
 "title": "Cockroach SQL",
 "description": "SQL dashboard: sql queries/transactions.",
 "tags": [ "cockroach" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster name",
    "query": "sys_uptime{job=~\".*cockroachdb-public\"}"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(sys_uptime{job=~\".*cockroachdb-public\",cluster=\"$cluster\"},instance)"
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "SQL Connections: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sql_conns{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"})",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Connections: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sql_conns{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sql_bytesin{job=~\".*cockroachdb-public\", cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(sql_bytesout{job=~\".*cockroachdb-public\", cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Bytes in/out: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "rate(sql_bytesin{job=~\".*cockroachdb-public\", cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval])",
     "legendFormat": "{{instance}} - in"
    },
    {
     "expr": "rate(sql_bytesout{job=~\".*cockroachdb-public\", cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval])",
     "legendFormat": "{{instance}} - out"
    }
   ]
  },
  {
   "title": "Queries: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sql_select_count{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "select"
    },
    {
     "expr": "sum(rate(sql_insert_count{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "insert"
    },
    {
     "expr": "sum(rate(sql_update_count{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "update"
    },
    {
     "expr": "sum(rate(sql_delete_count{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "delete"
    }
   ]
  },
  {
   "title": "Queries: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "rate(sql_select_count{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]) + rate(sql_insert_count{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]) + rate(sql_update_count{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]) + rate(sql_delete_count{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SQL Exec Latency: 99th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sql_exec_latency:rate1m:quantile_99{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transactions: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "rate(sql_txn_begin_count{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]) + rate(sql_txn_commit_count{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]) + rate(sql_txn_abort_count{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]) + rate(sql_txn_rollback_count{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SQL Exec Latency: 95th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sql_exec_latency:rate1m:quantile_95{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Schema Changes: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "rate(sql_ddl_count{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transactions: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sql_txn_begin_count{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "begin"
    },
    {
     "expr": "sum(rate(sql_txn_commit_count{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "commit"
    },
    {
     "expr": "sum(rate(sql_txn_abort_count{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "abort"
    },
    {
     "expr": "sum(rate(sql_txn_rollback_count{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "rollback"
    }
   ]
  },
  {
   "title": "Schema changes: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sql_ddl_count{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "DDL"
    }
   ]
  }
 ]
}
{
 "title": "Cockroach Replicas",
 "description": "Replicas dashboard: replica information and operations.",
 "tags": [ "cockroach" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster name",
    "query": "sys_uptime{job=~\".*cockroachdb-public\"}"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(sys_uptime{job=~\".*cockroachdb-public\",cluster=\"$cluster\"},instance)"
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Ranges: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(ranges{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "ranges"
    },
    {
     "expr": "sum(sum(replicas_leaders{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "raft leaders"
    },
    {
     "expr": "sum(sum(replicas_leaders_not_leaseholders{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "raft leaders not lease holders"
    },
    {
     "expr": "sum(sum(ranges_unavailable{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "unavailable"
    },
    {
     "expr": "sum(sum(ranges_underreplicated{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "under-replicated"
    }
   ]
  },
  {
   "title": "Ranges: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(ranges{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}} - ranges"
    },
    {
     "expr": "sum(ranges_unavailable{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}} - unavailable"
    }
   ]
  },
  {
   "title": "Raft Log: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(raftlog_behind{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "raft log behind"
    },
    {
     "expr": "sum(sum(rate(raftlog_truncated{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}[$rate_interval])) by (instance))",
     "legendFormat": "raft log truncated"
    },
    {
     "expr": "sum(sum(raftlog_selfbehind{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "raft log self behind"
    }
   ]
  },
  {
   "title": "Raft Log Behind: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "sum(raftlog_behind{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replicas: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(replicas{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Replicas"
    },
    {
     "expr": "sum(sum(replicas_quiescent{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Quiescent"
    },
    {
     "expr": "sum(sum(replicas{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}) by (instance) - sum(replicas_quiescent{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Quiescent Replicas: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sum(replicas_quiescent{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replica leaseholders per node: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(replicas_leaseholders{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replica leaseholders: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "sum(replicas_leaseholders{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replicas per node: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(replicas{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replicas: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "sum(replicas{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Logical bytes per node: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(keybytes{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}) by (instance) + sum(valbytes{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Live bytes: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "sum(livebytes{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Keys written per second per node: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum(rebalancing_writespersecond{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Keys written per second: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "sum(rebalancing_writespersecond{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Range Ops: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(sum(rate(range_splits{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}[$rate_interval])) by (instance))",
     "legendFormat": "splits"
    },
    {
     "expr": "sum(sum(rate(range_adds{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}[$rate_interval])) by (instance))",
     "legendFormat": "adds"
    },
    {
     "expr": "sum(sum(rate(range_removes{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}[$rate_interval])) by (instance))",
     "legendFormat": "removes"
    }
   ]
  },
  {
   "title": "Range Ops: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "targets": [
    {
     "expr": "sum(rate(range_splits{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}[$rate_interval])) by (instance) + sum(rate(range_adds{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}[$rate_interval])) by (instance) + sum(rate(range_removes{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}[$rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Snapshots: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ops", "label": "Snapshots" }
   ],
   "targets": [
    {
     "expr": "sum(sum(rate(range_snapshots_generated{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}[$rate_interval])) by (instance))",
     "legendFormat": "Generated"
    },
    {
     "expr": "sum(sum(rate(range_snapshots_normal_applied{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}[$rate_interval])) by (instance))",
     "legendFormat": "Normal-applied"
    },
    {
     "expr": "sum(sum(rate(range_snapshots_preemptive_applied{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}[$rate_interval])) by (instance))",
     "legendFormat": "Preemptive-applied"
    },
    {
     "expr": "sum(replicas_reserved{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"})",
     "legendFormat": "Reservations"
    }
   ]
  },
  {
   "title": "Snapshots: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 56 },
   "targets": [
    {
     "expr": "sum(rate(range_snapshots_generated{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}[$rate_interval])) by (instance)",
     "legendFormat": "{{instance}} - generated"
    },
    {
     "expr": "sum(rate(range_snapshots_normal_applied{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}[$rate_interval])) by (instance) + sum(rate(range_snapshots_preemptive_applied{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"}[$rate_interval])) by (instance)",
     "legendFormat": "{{instance}} - applied"
    }
   ]
  }
 ]
}
{
 "title": "Cockroach Runtime",
 "description": "Runtime dashboard: node status, including uptime, memory, and cpu.",
 "tags": [ "cockroach" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster name",
    "query": "sys_uptime{job=~\".*cockroachdb-public\"}"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(sys_uptime{job=~\".*cockroachdb-public\",cluster=\"$cluster\"},instance)"
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Nodes: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(up{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "All nodes"
    },
    {
     "expr": "count(up{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"} == 1)",
     "legendFormat": "Running nodes (prometheus)"
    },
    {
     "expr": "min(liveness_livenodes{cluster=\"$cluster\",job=~\".*cockroachdb-public\",instance=~\"$node\"})",
     "legendFormat": "Live nodes (node liveness heartbeats)"
    }
   ]
  },
  {
   "title": "Built Timestamp",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "build_timestamp{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Uptime: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sys_uptime{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "sys_uptime{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(sys_rss{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(sys_go_allocbytes{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "Go Allocated"
    },
    {
     "expr": "sum(sys_go_totalbytes{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "Go Total"
    },
    {
     "expr": "sum(sys_cgo_allocbytes{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "CGo Allocated"
    },
    {
     "expr": "sum(sys_cgo_totalbytes{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "CGo Total"
    }
   ]
  },
  {
   "title": "RSS: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sys_rss{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sys_goroutines{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "Goroutines"
    }
   ]
  },
  {
   "title": "Goroutines: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "sys_goroutines{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sys_gc_count{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "GC Runs"
    },
    {
     "expr": "sum(rate(sys_gc_pause_ns{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "GC Pauses"
    }
   ]
  },
  {
   "title": "GC Pauses: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "rate(sys_gc_pause_ns{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Time: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sys_cpu_user_ns{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "User"
    },
    {
     "expr": "sum(rate(sys_cpu_sys_ns{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "CPU Time: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "rate(sys_cpu_user_ns{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]) + rate(sys_cpu_sys_ns{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CGo Calls: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sys_cgocalls{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "calls/sec"
    }
   ]
  },
  {
   "title": "CGo Calls: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "rate(sys_cgocalls{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mean RPC Clock Offset: $node",
   "type": "graph",
   "description": "Mean clock offset with other nodes as measured by cockroach.",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "clock_offset_meannanos{job=~\".*cockroachdb-public\",cluster=\"$cluster\", instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Clock Offset: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "targets": [
    {
     "expr": "clock_offset_meannanos{job=~\".*cockroachdb-public\",cluster=\"$cluster\", instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Round Trip Latency: 50th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "round_trip_latency:rate1m:quantile_50{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Round Trip Latency: 50th Percentile",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 56 },
   "targets": [
    {
     "expr": "round_trip_latency:rate1m:quantile_50{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Round Trip Latency: 95th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "round_trip_latency:rate1m:quantile_95{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Round Trip Latency: 95th Percentile",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 63 },
   "targets": [
    {
     "expr": "round_trip_latency:rate1m:quantile_95{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Round Trip Latency: 99th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "round_trip_latency:rate1m:quantile_99{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Round Trip Latency: 99th Percentile",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 70 },
   "targets": [
    {
     "expr": "round_trip_latency:rate1m:quantile_99{job=~\".*cockroachdb-public\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}