harbor:
  enabled: true
  version: 2.8.0
  chart_version: 1.12.0
  url: https://helm.goharbor.io
  admin_password: 1nS3cur3P4ssw0rd
  secret_key: 2Ds7hlY9VHyKAcNd
  database:
    postgres:
      enabled: true
      password: 1ns3cur3P4ssw0rd
  ingress:
    enabled: true
    host: harbor
    notary_host: notary
  oauth:
    keycloak:
      enabled: true
      realm: default
      client_id: harbor
  s3:
    minio:
      enabled: true
      bucket: harbor
      access_key: harbor
      secret_key: 1ns3cur3P4ssw0rd
      ingress:
        enabled: true
        host: harbor-minio
        
        