harbor:
  version: 1.5.3
  adminPassword: Ch4ng3M3
  secretkey: 2Ds7hlY9VHyKAcNd
  databasePassword: Ch4ng3M34ls0
  coreIngressHost: harbor
  notaryIngressHost: notary
  nginxVersion: 2.2.0
  portalVersion: 2.2.0
  coreVersion: 2.2.0
  jobserviceVersion: 2.2.0
  registryVersion: 2.2.0
  controllerVersion: 2.2.0
  chartmuseumVersion: 2.2.0
  clairVersion: 2.1.3
  clairAdapterVersion: 2.1.3
  trivyAdapterVersion: 2.2.0
  notaryServerVersion: 2.2.0
  notarySignerVersion: 2.2.0
  databaseVersion: 2.2.0
  redisVersion: 2.2.0
  minio_image: docker.io/minio/minio:latest
  s3:
    accesskey: harbor
    secretkey: Ch4ng3M34ls0
    bucket: harbor
  # oauth:
  #   provider: keycloak
  #   keycloak:
  #     realm: default