nats_operator:
  image: docker.io/connecteverything/nats-operator:0.7.4
  stan_image: docker.io/synadia/nats-streaming-operator:0.4.2
  nats_cluster_version: 2.1.9
  stan_cluster_image: docker.io/amd64/nats-streaming:0.20.0-scratch
  prometheus_exporter_version: 0.6.0
