include:
  - kubernetes.csi.rook-edgefs.driver
  - kubernetes.csi.rook-edgefs.config
  - kubernetes.csi.rook-edgefs.namespace
  - kubernetes.csi.rook-edgefs.install
  - kubernetes.csi.rook-edgefs.ingress
  - kubernetes.csi.rook-edgefs.iscsi
  - kubernetes.csi.rook-edgefs.nfs
  - kubernetes.csi.rook-edgefs.s3
  - kubernetes.csi.rook-edgefs.s3x
  - kubernetes.csi.rook-edgefs.storageclass