apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gateway
  namespace: openfaas
  labels:
    app: gateway
spec:
  endpoints:
  - port: metrics
    path: /metrics
    interval: 5s
    scrapeTimeout: 30s
  selector:
    matchLabels:
      app: openfaas
      component: gateway
  namespaceSelector:
    matchNames:
      - openfaas