openebs:
  version: 2.5.0
  cstor_replication: 3
  mayastor_nbd_replication: 3
  mayastor_iscsi_replication: 3
  mayastor_nvmf_replication: 3
  csi_driver: https://raw.githubusercontent.com/kubernetes/csi-api/release-1.14/pkg/crd/manifests/csidriver.yaml
  csi_nodeinfo: https://raw.githubusercontent.com/kubernetes/csi-api/release-1.14/pkg/crd/manifests/csinodeinfo.yaml
  cstor_fstype: ext4
  default_storageclass:
    enabled: False
    name: mayastor-iscsi
  maya_apiserver_image: docker.io/openebs/m-apiserver:2.5.0
  provisioner_image: docker.io/openebs/openebs-k8s-provisioner:2.5.0
  snapshot_controller_image: docker.io/openebs/snapshot-controller:2.5.0
  snapshot_provisioner_image: docker.io/openebs/snapshot-provisioner:2.5.0
  node_disk_manager_image: docker.io/openebs/node-disk-manager:1.1.0
  node_disk_operator_image: docker.io/openebs/node-disk-operator:1.1.0
  admission_image: docker.io/openebs/admission-server:2.5.0
  localpv_image: docker.io/openebs/provisioner-localpv:2.5.0
  csi:
    cstor:
      resizer_image: quay.io/k8scsi/csi-resizer:v0.4.0
      snapshotter_image: quay.io/k8scsi/csi-snapshotter:v2.0.1
      snapshot_controller_image: quay.io/k8scsi/snapshot-controller:v2.0.1
      provisioner_image: quay.io/k8scsi/csi-provisioner:v1.6.0
      attacher_image: quay.io/k8scsi/csi-attacher:v2.0.0
      cluster_driver_registrar_image: quay.io/k8scsi/csi-cluster-driver-registrar:v1.0.1
      plugin_image: quay.io/openebs/cstor-csi-driver:1.11.0
      node_driver_registrar_image: quay.io/k8scsi/csi-node-driver-registrar:v1.0.1
    jiva:
      resizer_image: quay.io/k8scsi/csi-resizer:v0.3.0
      provisioner_image: quay.io/k8scsi/csi-provisioner:v1.5.0
      attacher_image: quay.io/k8scsi/csi-attacher:v2.0.0
      node_driver_registrar_image: quay.io/k8scsi/csi-node-driver-registrar:v1.2.0
    
